apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-challenge.fullname" . }}
  labels:
    app: {{ include "devops-challenge.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "devops-challenge.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
